### ISSUE TITLE
Update for TML v0.11.3

### ISSUE THREAD

**Issue by vizthex123** [0x0ade/TerrariaHooks#4]
Will it happen soon? Several mods don't work since this one hasn't updated yet.

**Comment by 0x0ade** [comment]
Sorry, I'm on vacation right now. Ideally, any mods which are still using the standalone version of TerrariaHooks should be updated to use tML 0.11's built-in version. I'll try to make the standalone version a compatibility "proxy" for 0.11 though.

**Comment by vizthex123** [comment]
> Sorry, I'm on vacation right now. Ideally, any mods which are still using the standalone version of TerrariaHooks should be updated to use tML 0.11's built-in version. I'll try to make the standalone version a compatibility "proxy" for 0.11 though.

Yeah if you could do that when you're done on vacation it would be great. Thanks.

**Comment by mattiaperry95** [comment]
Sorry to bother you, Im pretty new with the modding in terraria so if im wrong on something im sorry.
Anyway, i noticed that the current version of terriariaHooks on tModLoader is an outdated one. When i go to enable it it say: 
An error accured while loading TerrariaHooks
it Has been detected that this mod was built for TML v10.1.5
However, u r using tML v.11.5.
etc...
how can i solve this? thare are some workaround? if yes how?

**Comment by 0x0ade** [comment]
[I've finally updated the README. Please read it.](https://github.com/0x0ade/TerrariaHooks/blob/master/README.md#obsolete)

> Ideally, any mods which are still using the standalone version of TerrariaHooks should be updated to use tML 0.11's built-in version.

My initial plan was to convert this into a shim mod, but that ended up nowhere. Please update your mods, or tell mod devs to update their mods.
