### ISSUE TITLE
Update to TML v10.1.5

### ISSUE THREAD

**Issue by mattiaperry95** [0x0ade/TerrariaHooks#5]
Sorry to bother you, Im pretty new with the modding in terraria so if im wrong on something im sorry.
Anyway, i noticed that the current version of terriariaHooks on tModLoader is an outdated one. When i go to enable it it say:
An error accured while loading TerrariaHooks
it Has been detected that this mod was built for TML v10.1.5
However, u r using tML v.11.5.
etc...
how can i solve this? thare are some workaround? if yes how?

**Comment by mattiaperry95** [comment]
you there?

**Comment by imkSushi** [comment]
tModLoader added the features in TerrariaHooks to tModLoader in 0.11. You don't need this mod to access the features you likely want.

**Comment by 0x0ade** [comment]
[I've finally updated the README. Please read it.](https://github.com/0x0ade/TerrariaHooks/blob/master/README.md#obsolete)
