### ISSUE TITLE
Update for TML v0.11.6.2

### ISSUE THREAD

**Issue by vizthex123** [0x0ade/TerrariaHooks#6]
Will this be updated? I can't use Variable Potion Sickness or Player Resource Bars, and those are 2 of my favourite QoL mods.

If this won't be updated, is there anything else that works like them that doesn't need this mod?

**Comment by 0x0ade** [comment]
[I've finally updated the README. Please read it.](https://github.com/0x0ade/TerrariaHooks/blob/master/README.md#obsolete)
